import type { DataOrigin, VerificationStatus } from '../data/model';

export type LedgerVerificationStatus = VerificationStatus | 'unknown';

export interface LedgerClaimInput {
  entityType: 'FoodCulture' | 'Place' | 'Spot' | 'Route' | 'Story';
  entityId: string;
  entityName: string;
  claimId: string;
  claimLabel: string;
  claimKind?: 'factual' | 'editorial-narrative' | 'fieldwork-observation';
  canonicalValue?: string;
  displayedValue?: string;
  canonicalOrigin?: DataOrigin;
  presentationOrigin?: DataOrigin;
  verification: LedgerVerificationStatus;
  primarySourceName?: string;
  primarySourceUrl?: string;
  retrievedAt?: string;
  sourceUpdatedAt?: string;
  confirmedAt?: string;
  appSurface: string;
  canonicalSourceFile?: string;
  presentationSourceFile?: string;
  timeSensitive: boolean;
  timeSensitiveCaveat?: string;
  relevantIssue?: string;
  nextAction?: string;
  auditMetadata?: boolean;
}

export interface LedgerClaim extends LedgerClaimInput {
  mismatch: boolean;
}

const STATUS_ORDER: readonly LedgerVerificationStatus[] = [
  'conflict',
  'stale',
  'unknown',
  'needs_confirmation',
  'demo',
  'verified',
];

const ENTITY_ORDER: readonly LedgerClaimInput['entityType'][] = [
  'FoodCulture',
  'Story',
  'Route',
  'Place',
  'Spot',
];

function comparisonValue(value: string): string {
  return value.replaceAll('\r\n', '\n').replaceAll('\r', '\n').replace(/\s+/g, ' ').trim();
}

export function compileLedgerClaims(inputs: readonly LedgerClaimInput[]): LedgerClaim[] {
  return inputs.map((input) => ({
    ...input,
    mismatch: input.canonicalValue !== undefined
      && input.displayedValue !== undefined
      && comparisonValue(input.canonicalValue) !== comparisonValue(input.displayedValue),
  })).sort(compareClaims);
}

function compareText(left: string, right: string): number {
  if (left === right) return 0;
  return left < right ? -1 : 1;
}

function compareClaims(left: LedgerClaim, right: LedgerClaim): number {
  return ENTITY_ORDER.indexOf(left.entityType) - ENTITY_ORDER.indexOf(right.entityType)
    || compareText(left.entityId, right.entityId)
    || compareText(left.claimId, right.claimId);
}

function markdown(value: string | undefined): string {
  if (value === undefined || value === '') return '—';
  return value.replaceAll('|', '\\|').replace(/\r?\n|\r/g, '<br>');
}

function source(claim: LedgerClaim): string {
  if (!claim.primarySourceName) return '—';
  if (!claim.primarySourceUrl) return markdown(claim.primarySourceName);
  return `[${markdown(claim.primarySourceName)}](${claim.primarySourceUrl})`;
}

function queueLines(claims: readonly LedgerClaim[], empty: string): string[] {
  if (claims.length === 0) return [empty];
  return claims.map((claim) =>
    `- \`${claim.entityId} + ${claim.claimId}\` — ${claim.claimLabel}${claim.nextAction ? `: ${claim.nextAction}` : ''}`);
}

function groupedQueueLines(claims: readonly LedgerClaim[], empty: string): string[] {
  if (claims.length === 0) return [empty];
  const byEntity = new Map<string, LedgerClaim[]>();
  for (const claim of claims) {
    const current = byEntity.get(claim.entityId) ?? [];
    current.push(claim);
    byEntity.set(claim.entityId, current);
  }
  return [...byEntity].map(([entityId, entityClaims]) =>
    `- \`${entityId}\` — ${entityClaims.map((claim) => `\`${claim.claimId}\``).join(', ')}`);
}

export function renderDataVerificationLedger(inputs: readonly LedgerClaimInput[]): string {
  const claims = compileLedgerClaims(inputs);
  const lines = [
    '# Data Verification Ledger',
    '',
    '> Generated deterministically from current repository records. Do not edit this file by hand.',
    '',
    'Regenerate with `pnpm data:ledger`; validate the committed artifact with `pnpm data:ledger:check`.',
    '',
    '- `unknown` rows are report-only gaps in the bounded visible-field inventory; they do not populate canonical Product data.',
    '- A mismatch compares the actual canonical and presentation values after line-ending and whitespace normalization only. This report does not reconcile either value.',
    '- Origin, verification, checked/retrieved date, source-updated date, and `confirmedAt` are independent. Source recency never promotes a claim to `verified`.',
    '- The Evidence column is intentionally reserved and blank for #334; this ledger does not capture or manage evidence files.',
    '',
    '## Status summary',
    '',
    '| Verification | Claims |',
    '| --- | ---: |',
    ...STATUS_ORDER.map((status) =>
      `| ${status} | ${claims.filter((claim) => claim.verification === status).length} |`),
    '',
    '## High-priority review queues',
    '',
    '### Conflicts',
    '',
    ...queueLines(claims.filter((claim) => claim.verification === 'conflict'), 'No conflict-status claims.'),
    '',
    '### Stale time-sensitive facts',
    '',
    ...queueLines(
      claims.filter((claim) => claim.verification === 'stale' && claim.timeSensitive),
      'No stale time-sensitive claims.',
    ),
    '',
    '### Visible or required unknown facts',
    '',
    ...groupedQueueLines(
      claims.filter((claim) => claim.verification === 'unknown'),
      'No required unknown claims.',
    ),
    '',
    '## Canonical ↔ presentation mismatches',
    '',
  ];

  const mismatches = claims.filter((claim) => claim.mismatch);
  lines.push(...(mismatches.length === 0
    ? ['No mismatches detected.']
    : mismatches.map((claim) =>
        `- \`${claim.entityId} + ${claim.claimId}\`: canonical “${markdown(claim.canonicalValue)}”; displayed “${markdown(claim.displayedValue)}”`)));

  lines.push(
    '',
    '## Claims requiring explicit audit metadata',
    '',
    ...groupedQueueLines(
      claims.filter((claim) => claim.auditMetadata),
      'No claims require explicit audit metadata.',
    ),
    '',
    '## Claim inventory',
    '',
    '| Entity type | Entity ID | Entity name | Claim ID | Claim kind | Field / claim | Canonical value | Displayed value | Origin | Verification | Primary source | Checked / retrieved date | Source updated date | Confirmed date | Time-sensitive | App surface | Canonical source file | Presentation source file | Relevant Issue / PR | Mismatch | Evidence | Next action / note |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...claims.map((claim) => `| ${claim.entityType} | ${markdown(claim.entityId)} | ${markdown(claim.entityName)} | ${markdown(claim.claimId)} | ${claim.claimKind ?? 'factual'} | ${markdown(claim.claimLabel)} | ${markdown(claim.canonicalValue)} | ${markdown(claim.displayedValue)} | canonical: ${claim.canonicalOrigin ?? '—'}; presentation: ${claim.presentationOrigin ?? '—'} | ${claim.verification} | ${source(claim)} | ${markdown(claim.retrievedAt)} | ${markdown(claim.sourceUpdatedAt)} | ${markdown(claim.confirmedAt)} | ${claim.timeSensitive ? `yes${claim.timeSensitiveCaveat ? ` — ${markdown(claim.timeSensitiveCaveat)}` : ''}` : 'no'} | ${markdown(claim.appSurface)} | ${markdown(claim.canonicalSourceFile)} | ${markdown(claim.presentationSourceFile)} | ${markdown(claim.relevantIssue)} | ${claim.mismatch ? 'yes' : 'no'} |  | ${markdown(claim.nextAction)} |`),
  );

  return `${lines.join('\n')}\n`;
}
