import type { MapEntry } from './types';

/**
 * Machine-readable Figma surface → implementation → Issue map (Issues #233 / #242).
 *
 * The watched list is the post-#246 reconciliation of the current visible
 * KiKi Figma page. The human-readable mirror lives in
 * `docs/design/figma-implementation-map.md`; `map.test.ts` keeps both node
 * sets and surface names in sync.
 */
export const IMPLEMENTATION_MAP: MapEntry[] = [
  {
    nodeId: '1:95',
    surface: 'Landing',
    journeyRole: 'Journey entry',
    implementation: 'LandingPage + ReturningHome (src/pages/s0s3/LandingPage.tsx)',
    codeFiles: ['src/pages/s0s3/LandingPage.tsx'],
    issues: ['#201', '#217'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '2:21',
    surface: 'Food Profile welcome (start-only variant)',
    journeyRole: 'Food-profile intro alternate',
    implementation: 'FoodProfilePage IntroCard start action',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx'],
    issues: ['#201', '#217', '#242'],
    status: 'MATCH',
    watched: true,
    note: 'Current Figma alternate omits the browse action; the shared IntroCard covers the start state.',
  },
  {
    nodeId: '2:245',
    surface: 'Food Profile welcome',
    journeyRole: 'Food-profile intro',
    implementation: 'FoodProfilePage IntroCard (fpStartCta / fpBrowseCta)',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx'],
    issues: ['#201', '#217'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '2:312',
    surface: 'Nickname prompt',
    journeyRole: 'Nickname step before input',
    implementation: 'FoodProfilePage NicknameStep reopen state',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx'],
    issues: ['#201', '#217', '#246'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '2:548',
    surface: 'Nickname submitted',
    journeyRole: 'Nickname step completed state',
    implementation: 'FoodProfilePage nickname transcript',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx'],
    issues: ['#201', '#217', '#246'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '2:383',
    surface: 'Nickname input modal',
    journeyRole: 'Nickname input presentation state',
    implementation: 'FoodProfilePage FigmaInputModal (nickname)',
    codeFiles: [
      'src/pages/s0s3/FoodProfilePage.tsx',
      'src/pages/s0s3/figma-conversation-parity.css',
      'src/i18n/resources.ts',
    ],
    issues: ['#201', '#208', '#246'],
    status: 'MATCH',
    watched: true,
    note: 'Implemented by PR #247. Escape/backdrop cancel and focus mechanics are the documented 375px engineering adaptation; nickname remains localStorage-only.',
  },
  {
    nodeId: '2:623',
    surface: 'Food Profile interview Q1 (allergy) active',
    journeyRole: 'Dietary interview step 1/4',
    implementation: 'PHASE1_INTERVIEW allergy options + send action',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#217', '#246'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '3:854',
    surface: 'Food Profile interview Q1 (allergy) completed',
    journeyRole: 'Dietary interview step 1/4 completed state',
    implementation: 'FoodProfilePage sequential transcript after allergy answer',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#217', '#242'],
    status: 'MATCH',
    watched: true,
    note: 'Semantic correction from the former Q2 label: live node text is the allergy question with the submitted allergy answer.',
  },
  {
    nodeId: '3:959',
    surface: 'Food Profile interview Q2 (diet) active',
    journeyRole: 'Dietary interview step 2/4',
    implementation: 'PHASE1_INTERVIEW diet options + send action',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#217', '#242'],
    status: 'MATCH',
    watched: true,
    note: 'Semantic correction from the former Q3 label: live node text is the everyday-diet question.',
  },
  {
    nodeId: '3:1081',
    surface: 'Food Profile interview Q2 (diet) completed',
    journeyRole: 'Dietary interview step 2/4 completed state',
    implementation: 'FoodProfilePage sequential transcript after diet answer',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#217', '#242'],
    status: 'MATCH',
    watched: true,
    note: 'Semantic correction from the former Q4 label: live node text is the diet question with its submitted answer.',
  },
  {
    nodeId: '3:1203',
    surface: 'Food Profile interview Q3 (religion) active',
    journeyRole: 'Dietary interview step 3/4',
    implementation: 'PHASE1_INTERVIEW religion options + send action',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#217', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '3:1320',
    surface: 'Food Profile interview Q3 (religion) completed',
    journeyRole: 'Dietary interview step 3/4 completed state',
    implementation: 'FoodProfilePage sequential transcript after religion answer',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#217', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '3:1500',
    surface: 'Food Profile interview Q4 (dislikes) active',
    journeyRole: 'Dietary interview step 4/4',
    implementation: 'PHASE1_INTERVIEW dislikes options + send action',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#217', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '3:1599',
    surface: 'Food Profile interview Q4 (dislikes) completed',
    journeyRole: 'Dietary interview step 4/4 completed state',
    implementation: 'FoodProfilePage sequential transcript after dislike answer',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#217', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '3:1702',
    surface: 'Food Profile summary',
    journeyRole: 'Summary + edit note',
    implementation: 'FoodProfilePage setup summary and neutral profile save',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#224'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '3:1835',
    surface: 'Post-profile fork',
    journeyRole: 'Food-profile → travel fork',
    implementation: 'FoodProfilePage ForkStep (recommend / browse)',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#224'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '3:772',
    surface: 'Food Profile free-input modal',
    journeyRole: 'Presentation-only free-input state',
    implementation: 'FoodProfilePage FigmaInputModal (interview other)',
    codeFiles: [
      'src/pages/s0s3/FoodProfilePage.tsx',
      'src/pages/s0s3/figma-conversation-parity.css',
      'src/i18n/resources.ts',
    ],
    issues: ['#201', '#208', '#246'],
    status: 'MATCH',
    watched: true,
    note: 'Implemented by PR #247. Text is presentation-only and never becomes a dietary safety claim or durable profile field.',
  },
  {
    nodeId: '3:1952',
    surface: 'ReturningHome',
    journeyRole: 'Returning-visitor home + history',
    implementation: 'ReturningHome + HistorySection + prototype bottom navigation',
    codeFiles: ['src/pages/s0s3/LandingPage.tsx', 'src/pages/s0s3/history-section.tsx', 'src/app/PrototypeShell.tsx'],
    issues: ['#201', '#92'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '4:2101',
    surface: 'Experience',
    journeyRole: 'Exploration Q1',
    implementation: 'ExplorationWizardPage S2 Q1',
    codeFiles: ['src/pages/s0s3/ExplorationWizardPage.tsx', 'src/pages/s0s3/phase1-exploration.ts'],
    issues: ['#201', '#217', '#230'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '8:2436',
    surface: 'Departure',
    journeyRole: 'Exploration Q2',
    implementation: 'ExplorationWizardPage area chips + travel pairs',
    codeFiles: ['src/pages/s0s3/ExplorationWizardPage.tsx', 'src/pages/s0s3/phase1-exploration.ts'],
    issues: ['#201', '#206', '#230'],
    status: 'MATCH',
    watched: true,
    note: 'Departure-point search remains a presentation-only/deferred adaptation (#206).',
  },
  {
    nodeId: '23:3131',
    surface: 'Travel tolerance',
    journeyRole: 'Exploration Q3',
    implementation: 'ExplorationWizardPage S2 Q3',
    codeFiles: ['src/pages/s0s3/ExplorationWizardPage.tsx', 'src/pages/s0s3/phase1-exploration.ts'],
    issues: ['#201', '#206', '#230'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '23:3207',
    surface: 'Duration',
    journeyRole: 'Exploration Q4',
    implementation: 'ExplorationWizardPage S2 Q4',
    codeFiles: ['src/pages/s0s3/ExplorationWizardPage.tsx', 'src/pages/s0s3/phase1-exploration.ts'],
    issues: ['#201', '#206', '#230'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '23:3262',
    surface: 'Taste + Theme',
    journeyRole: 'Exploration Q5',
    implementation: 'ExplorationWizardPage S2 Q5 (taste + theme)',
    codeFiles: ['src/pages/s0s3/ExplorationWizardPage.tsx', 'src/pages/s0s3/phase1-exploration.ts'],
    issues: ['#201', '#206', '#230'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '23:3380',
    surface: 'Result',
    journeyRole: 'Match result',
    implementation: 'ResultPage candidate result + Story CTA',
    codeFiles: ['src/pages/s0s3/ResultPage.tsx'],
    issues: ['#201', '#217', '#241'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '52:3995',
    surface: 'Story',
    journeyRole: 'Food-culture story',
    implementation: 'StoryPage hero + editorial sections + nearby spots',
    codeFiles: ['src/pages/StoryPage.tsx', 'src/pages/StoryPage.css', 'src/i18n/resources.ts'],
    issues: ['#201', '#224', '#241'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '119:254',
    surface: 'Story route transition presentation reference',
    journeyRole: 'Story → Route presentation transition',
    implementation: 'Existing Story CTA → source-backed Route for current journey/candidate (no runtime generation)',
    codeFiles: ['src/pages/StoryPage.tsx'],
    issues: ['#201', '#208', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: true,
    note: 'PRESENTATION_ONLY per the #242 Product decision: the existing Story → Route CTA is the conceptual trigger, direct navigation resolves the existing source-backed route, no artificial delay or async generation lifecycle is added, and saving remains the explicit Route action.',
  },
  {
    nodeId: '119:681',
    surface: 'Route',
    journeyRole: 'Generated route page',
    implementation: 'RoutePage route timeline + save action',
    codeFiles: ['src/pages/RoutePage.tsx', 'src/pages/route-context.ts'],
    issues: ['#201', '#92', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '122:889',
    surface: 'Route saved state',
    journeyRole: 'Route save confirmation / My Route affordance',
    implementation: 'RoutePage save state + MyRoutePage saved route list',
    codeFiles: ['src/pages/RoutePage.tsx', 'src/pages/MyRoutePage.tsx'],
    issues: ['#92', '#201', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '125:1752',
    surface: 'Spot',
    journeyRole: 'Route → Spot detail',
    implementation: 'SpotPage sourced place detail + action boundary',
    codeFiles: ['src/pages/SpotPage.tsx', 'src/pages/route-context.ts'],
    issues: ['#92', '#201', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '62:4983',
    surface: 'Story nearby spot experience group',
    journeyRole: 'Story content reference group',
    implementation: 'StoryPage nearby spot cards',
    codeFiles: ['src/pages/StoryPage.tsx', 'src/pages/StoryPage.css'],
    issues: ['#224', '#242'],
    status: 'MATCH',
    watched: true,
    note: 'Content grouping, not a standalone route; covered by the Story nearby section.',
  },
  {
    nodeId: '62:4830',
    surface: 'Story nearby spots group',
    journeyRole: 'Story content reference group',
    implementation: 'StoryPage nearby spots section',
    codeFiles: ['src/pages/StoryPage.tsx', 'src/pages/StoryPage.css'],
    issues: ['#224', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '62:4616',
    surface: 'Spot related card group',
    journeyRole: 'Spot content reference group',
    implementation: 'SpotPage related / route-context cards',
    codeFiles: ['src/pages/SpotPage.tsx', 'src/pages/route-spot.css'],
    issues: ['#224', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '62:4615',
    surface: 'Spot card collection group',
    journeyRole: 'Spot content reference group',
    implementation: 'SpotPage place-card collection',
    codeFiles: ['src/pages/SpotPage.tsx', 'src/pages/route-spot.css'],
    issues: ['#224', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '60:4426',
    surface: 'Story long-form content reference',
    journeyRole: 'Story editorial content group',
    implementation: 'StoryPage numbered editorial sections',
    codeFiles: ['src/pages/StoryPage.tsx', 'src/pages/StoryPage.css'],
    issues: ['#224', '#242'],
    status: 'MATCH',
    watched: true,
    note: 'Large Figma content group; represented by the responsive Story page rather than a separate runtime route.',
  },
  {
    nodeId: '60:4385',
    surface: 'Story mobile long-form content reference',
    journeyRole: 'Story editorial content group',
    implementation: 'StoryPage responsive editorial sections',
    codeFiles: ['src/pages/StoryPage.tsx', 'src/pages/StoryPage.css'],
    issues: ['#224', '#242'],
    status: 'MATCH',
    watched: true,
  },
  {
    nodeId: '52:4092',
    surface: 'Sticky story CTA',
    journeyRole: 'Story → Route convenience CTA',
    implementation: 'StoryPage sticky CTA',
    codeFiles: ['src/pages/StoryPage.tsx', 'src/pages/StoryPage.css', 'src/i18n/resources.ts'],
    issues: ['#232', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: true,
    note: 'Documented presentation convenience deviation; not a new route-generation semantic.',
  },
  {
    nodeId: '23:3620',
    surface: 'Route-generation CTA reference',
    journeyRole: 'Story → Route reference component',
    implementation: 'StoryPage current CTA copy and route link',
    codeFiles: ['src/pages/StoryPage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#208', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: true,
    note: 'Reference component is accounted for; the unresolved behavior is the separate 119:254 loading state.',
  },
  {
    nodeId: '8:2608',
    surface: 'Departure search dialog',
    journeyRole: 'Exploration Q2 search reference',
    implementation: 'ExplorationWizardPage presentation-only search affordance',
    codeFiles: ['src/pages/s0s3/ExplorationWizardPage.tsx', 'src/i18n/resources.ts'],
    issues: ['#206', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: true,
    note: 'Search is deferred and never acts as a geocoder or route optimizer.',
  },
  {
    nodeId: '8:2903',
    surface: 'Departure search dialog alternate',
    journeyRole: 'Exploration Q2 search reference alternate',
    implementation: 'ExplorationWizardPage presentation-only search affordance',
    codeFiles: ['src/pages/s0s3/ExplorationWizardPage.tsx', 'src/i18n/resources.ts'],
    issues: ['#206', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: true,
    note: 'Accounted for as the same deferred/presentation-only search contract as 8:2608.',
  },
  {
    nodeId: '1:43',
    surface: 'Destination search field reference',
    journeyRole: 'Exploration departure reference component',
    implementation: 'ExplorationWizardPage area selection controls',
    codeFiles: ['src/pages/s0s3/ExplorationWizardPage.tsx'],
    issues: ['#206', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: true,
    note: 'Current implementation uses bounded area choices; free-form geocoding remains deferred.',
  },
  {
    nodeId: '1:23',
    surface: 'Prototype bottom navigation reference',
    journeyRole: 'Prototype shell chrome',
    implementation: 'PrototypeShell fixture navigation + AppShell production IA',
    codeFiles: ['src/app/PrototypeShell.tsx', 'src/app/AppShell.tsx'],
    issues: ['#92', '#203', '#226', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: true,
    note: 'Figma labels are accounted for as prototype chrome; current Product IA remains Home / Discover / MOGU / My.',
  },
  // Current bridge inventory contains these historical nodes, but they are not
  // current meaningful product surfaces and therefore are not watched.
  {
    nodeId: '62:5023',
    surface: 'Story footer CTA (retired node)',
    journeyRole: 'Retired Figma reference',
    implementation: 'Covered by current Story CTA surfaces',
    codeFiles: ['src/pages/StoryPage.tsx', 'src/i18n/resources.ts'],
    issues: ['#235', '#236', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: false,
    note: 'Not present in the current bridge top-level inventory; retained only as a historical map alias.',
  },
  {
    nodeId: '55:4166',
    surface: 'Route (retired node)',
    journeyRole: 'Retired Figma reference',
    implementation: 'Covered by current Route frame 119:681',
    codeFiles: ['src/pages/RoutePage.tsx'],
    issues: ['#201', '#92', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: false,
    note: 'Not present in the current bridge top-level inventory; replaced by 119:681.',
  },
  {
    nodeId: '23:3621',
    surface: 'Route dialog CTA (retired node)',
    journeyRole: 'Retired Figma reference',
    implementation: 'Covered by current reference node 23:3620',
    codeFiles: ['src/pages/StoryPage.tsx', 'src/i18n/resources.ts'],
    issues: ['#201', '#208', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: false,
    note: 'Not present in the current bridge top-level inventory; replaced by 23:3620.',
  },
  {
    nodeId: '62:4620',
    surface: 'Spot category pills (retired node)',
    journeyRole: 'Retired Figma reference',
    implementation: 'Covered by current Spot groups 62:4616 and 62:4615',
    codeFiles: ['src/pages/SpotPage.tsx', 'src/pages/route-spot.css'],
    issues: ['#232', '#224', '#242'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: false,
    note: 'Not present in the current bridge top-level inventory; retained only as a historical map alias.',
  },
  {
    nodeId: null,
    surface: 'Prototype shell chrome',
    journeyRole: 'Prototype chrome',
    implementation: 'PrototypeShell compact header (locale + reset)',
    codeFiles: ['src/app/PrototypeShell.tsx'],
    issues: ['#232'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: false,
    note: 'Cross-cutting engineering adaptation without one Figma node.',
  },
  {
    nodeId: null,
    surface: 'Sequential chat model',
    journeyRole: 'Exploration / food-profile presentation',
    implementation: 'LINE/ChatGPT sequential reveal + scroll',
    codeFiles: [
      'src/pages/s0s3/conversation.tsx',
      'src/pages/s0s3/ExplorationWizardPage.tsx',
      'src/pages/s0s3/FoodProfilePage.tsx',
    ],
    issues: ['#230', '#232'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: false,
    note: 'Cross-cutting engineering adaptation without one Figma node.',
  },
  {
    nodeId: null,
    surface: 'No page-level 次へ',
    journeyRole: 'Exploration presentation',
    implementation: '#230 sequential action contract',
    codeFiles: ['src/pages/s0s3/ExplorationWizardPage.tsx', 'src/pages/s0s3/FoodProfilePage.tsx'],
    issues: ['#230'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: false,
  },
  {
    nodeId: null,
    surface: 'Body font',
    journeyRole: 'Conversation typography',
    implementation: 'Zen Kaku Gothic New (CJK)',
    codeFiles: ['src/ui/tokens.css'],
    issues: ['#232'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: false,
  },
  {
    nodeId: null,
    surface: 'Question text ink',
    journeyRole: 'FP / exploration question legibility',
    implementation: 'WCAG AA question ink treatment',
    codeFiles: ['src/pages/s0s3/FoodProfilePage.css'],
    issues: ['#232'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: false,
  },
  {
    nodeId: null,
    surface: 'Experience tile caption',
    journeyRole: 'Experience presentation',
    implementation: 'Mobile legibility caption overlay',
    codeFiles: ['src/pages/s0s3/ExplorationWizardPage.tsx', 'src/pages/s0s3/figma-conversation-parity.css'],
    issues: ['#232'],
    status: 'INTENTIONALLY_DIFFERENT',
    watched: false,
  },
];

const byNodeId = new Map<string, MapEntry>();
for (const entry of IMPLEMENTATION_MAP) {
  if (entry.nodeId !== null) byNodeId.set(entry.nodeId, entry);
}

/** Look up implementation/Issue metadata by Figma node id. */
export function lookupMapEntry(nodeId: string): MapEntry | null {
  return byNodeId.get(nodeId) ?? null;
}

/** All current Figma surfaces in the watchlist. */
export function watchedMapEntries(): MapEntry[] {
  return IMPLEMENTATION_MAP.filter((entry) => entry.watched && entry.nodeId !== null);
}
